version: '3.0'
 
services:
    dbNomadas:
        image: "mcr.microsoft.com/mssql/server:2019-latest"
        environment:
            ACCEPT_EULA: "Y"
            MSSQL_PID: Express
            SA_PASSWORD: ${DB_PASSWORD}
        network_mode: host
        ports:
        - "1433:1433"
        volumes:
            - sqlvolume:/var/opt/mssql
    webapi:
        image: goodbytes23/nomadas.network:latest
        build:
            context: .
            dockerfile: Dockerfile.develop
        network_mode: host
        volumes:
            - ./:/src
        ports:
            - "5000:5000"
        environment: 
            DB_PASSWORD: ${DB_PASSWORD}
            ADMIN_LOGIN: ${ADMIN_LOGIN}
            DB_SERVER: ${DB_SERVER}
            DB_NAME: ${DB_NAME}
            DB_PORT: ${DB_PORT}
            ASPNETCORE_ENVIRONMENT: Development
        depends_on:
            - dbNomadas
volumes:
    sqlvolume: